/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ajdeveloppement_macosx_MacOSXAuthProcess */

#ifndef _Included_org_ajdeveloppement_macosx_MacOSXAuthProcess
#define _Included_org_ajdeveloppement_macosx_MacOSXAuthProcess
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ajdeveloppement_macosx_MacOSXAuthProcess_DEFAULT
#define org_ajdeveloppement_macosx_MacOSXAuthProcess_DEFAULT 0L

/*
 * Class:     org_ajdeveloppement_macosx_MacOSXAuthProcess
 * Method:    rootExec
 * Signature: (JILjava/lang/String;[Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;[I)I
 */
JNIEXPORT jint JNICALL Java_org_ajdeveloppement_macosx_MacOSXAuthProcess_rootExec
  (JNIEnv *, jclass, jlong, jint, jstring, jobjectArray, jobject, jobject, jobject, jintArray);
/*
 * Class:     org_ajdeveloppement_macosx_MacOSXAuthProcess
 * Method:    waitForProcessExit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ajdeveloppement_macosx_MacOSXAuthProcess_waitForProcessExit
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ajdeveloppement_macosx_MacOSXAuthProcess
 * Method:    destroyProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ajdeveloppement_macosx_MacOSXAuthProcess_destroyProcess
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
